site_name: PGVerse Documentation
site_description: Documentation for the PGVerse project
site_url: https://yourprojectsite.com

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_signature_annotations: true
            merge_init_into_class: true
            show_inheritance: true
            members_order: source
            filters:
              - "!^_"
            heading_level: 2

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Reference:
      - Main Modules:
          - bielik_app: reference/bielik_app.md
          - DataBaseApp: reference/DataBaseApp.md
          - enviromental_variables: reference/enviromental_variables.md
          - integrated_rag_app: reference/integrated_rag_app.md
          - main_window: reference/main_window.md
          - rag_utils: reference/rag_utils.md
      - bin/schematy_code:
          - model: reference/bin/schematy_code/model.md
      - charts:
          - charts: reference/charts/charts.md
          - axis_intersection_detector: reference/charts/axis_intersection_detector/main.md
          - charts_axes_detect:
              - axes_detection: reference/charts/charts_axes_detect/axes_detection.md
              - axes_interpretation: reference/charts/charts_axes_detect/axes_interpretation.md
              - chart_preprocessing: reference/charts/charts_axes_detect/chart_preprocessing.md
              - chart_run: reference/charts/charts_axes_detect/chart_run.md
              - generate_axes_report: reference/charts/charts_axes_detect/generate_axes_report.md
              - run_text_extraction: reference/charts/charts_axes_detect/run_text_extraction.md
              - small_text_ocr: reference/charts/charts_axes_detect/small_text_ocr.md
          - data_analyzer:
              - example_charts: reference/charts/data_analyzer/example_charts.md
              - symbolic_regressor: reference/charts/data_analyzer/symbolic_regressor.md
              - test_data_analyzer: reference/charts/data_analyzer/test_data_analyzer.md
          - read_chart:
              - read_chart: reference/charts/read_chart/read_chart.md
      - ocr/scalanie_ocr:
          - detekcja_elementow: reference/ocr/scalanie_ocr/detekcja_elementow.md
          - model_wykrywanie_pismo_odreczne: reference/ocr/scalanie_ocr/model_wykrywanie_pismo_odreczne.md
          - mozg_ocr_updated: reference/ocr/scalanie_ocr/mozg_ocr_updated.md
          - mozg_ocr: reference/ocr/scalanie_ocr/mozg_ocr.md
          - ocr_ekstrakcja_z_tabel_img2_paddle: reference/ocr/scalanie_ocr/ocr_ekstrakcja_z_tabel_img2_paddle.md
          - ocr_tabele_obrazki: reference/ocr/scalanie_ocr/ocr_tabele_obrazki.md
          - ocr_tabele_wzory_obrazki: reference/ocr/scalanie_ocr/ocr_tabele_wzory_obrazki.md
          - ocr_wzory_latex: reference/ocr/scalanie_ocr/ocr_wzory_latex.md
          - wyodrebniony_tekst: reference/ocr/scalanie_ocr/wyodrebniony_tekst.md
      - rag_codes/rag_metrics:
          - bertscore_graph: reference/rag_codes/rag_metrics/bertscore_graph.md
          - BERTscore: reference/rag_codes/rag_metrics/BERTscore.md
      - schematics:
          - metrics: reference/schematics/metrics.md
          - schematics: reference/schematics/schematics.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html